const starter=[{id:1,title:'写下人生游戏的核心设想',note:'主线 · 第一章',type:'主线',xp:30,done:false},{id:2,title:'整理书桌上的一个区域',note:'支线 · 约15分钟',type:'支线',xp:12,done:false},{id:3,title:'到户外走一走',note:'日常 · 不限速度',type:'日常',xp:10,done:true},{id:4,title:'拍下今天最喜欢的画面',note:'随机 · 今晚前',type:'随机',xp:18,done:false}];
let state={tasks:starter,coins:126,energy:72,page:'today',owned:[]};try{state={...state,...JSON.parse(localStorage.getItem('star-life-v2')||'{}')}}catch{};
const $=s=>document.querySelector(s), save=()=>localStorage.setItem('star-life-v2',JSON.stringify(state));
function toast(t){let e=$('#toast');e.textContent=t;e.hidden=false;clearTimeout(window.tt);window.tt=setTimeout(()=>e.hidden=true,2200)}
function taskHTML(t){return `<article class="quest ${t.done?'done':''}"><button class="check" data-task="${t.id}">${t.done?'✓':''}</button><div><span class="rarity ${t.type}">${t.type}</span><b>${t.title}</b><small>${t.note}</small></div><strong>+${t.xp}<small> XP</small></strong></article>`}
const views={
today:()=>{let d=state.tasks.filter(x=>x.done).length,p=Math.round(d/state.tasks.length*100),face=p===100?'😎':p>=50?'😊':p>0?'🙂':'😴';return `<div class="grow-head"><h1>今天</h1><button data-action="energy">⚙</button></div><div class="week-strip">${[6,7,8,9,10,11,12].map((n,i)=>`<button class="${n===11?'now':''}"><b>${n}</b><span>${i<5?(i%2?'😴':'🌞'):i===5?face:'●'}</span></button>`).join('')}</div><section class="perfect"><div class="progress-ring" style="--p:${p*3.6}deg"><div><span>${face}</span><b>${p}%</b><small>Perfect Day</small></div></div><p>${p===100?'太棒了！今天的冒险已经圆满完成。':p>=50?'状态不错，再推进一小步就更接近完美的一天。':'加油，安安！不需要做很多，先完成最小的一步。'}</p></section><div class="section-row"><h2>今日冒险</h2><button data-action="add">编辑 ›</button></div><div class="grow-tasks">${state.tasks.map(t=>`<article class="grow-task ${t.done?'done':''}"><button data-task="${t.id}"><span>${t.done?'✓':t.type==='主线'?'⚔':t.type==='随机'?'🎲':'✦'}</span><div><b>${t.title}</b><small>${t.note} · +${t.xp} XP</small><em><i style="width:${t.done?'100':'12'}%"></i></em></div></button></article>`).join('')}</div><button class="random-fab" data-action="random">＋ 随机任务</button>`},
quests:()=>`<div class="page-head"><span>QUEST GUILD</span><h1>任务公会</h1><p>把真实目标拆成一场场可以完成的冒险。</p></div><div class="filter"><button class="active">全部</button><button>主线</button><button>支线</button><button>日常</button></div><section class="card guild"><div class="quest-list">${state.tasks.map(taskHTML).join('')}</div><button class="primary" data-action="add">＋ 发布新任务</button></section>`,
journey:()=>`<div class="page-head"><span>WORLD MAP</span><h1>你的旅程</h1><p>每一次真实行动，都会点亮地图上的一小块。</p></div><section class="map card"><div class="path"></div><button class="node complete" style="--x:12%;--y:72%"><b>✓</b><span>序章<br><small>重新出发</small></span></button><button class="node complete" style="--x:34%;--y:45%"><b>✓</b><span>第11章<br><small>整理与告别</small></span></button><button class="node current" style="--x:58%;--y:64%"><b>12</b><span>当前章节<br><small>盛夏行动</small></span></button><button class="node locked" style="--x:79%;--y:30%"><b>🔒</b><span>第13章<br><small>尚未解锁</small></span></button><div class="map-note">再完成 <b>3</b> 个任务，开启下一处区域</div></section>`,
rewards:()=>`<div class="page-head"><span>REWARD SHOP</span><h1>奖励商店</h1><p>星币不是分数，而是你允许自己享受生活的凭证。</p></div><div class="shop">${[['☕','悠闲咖啡时间',60],['🎬','无负担电影夜',100],['🌿','半日自由探索',180],['🎁','神秘奖励箱',240]].map((r,i)=>`<article class="card reward"><span>${r[0]}</span><h3>${r[1]}</h3><p>${i%2?'为努力后的自己留一段完整时间':'把这一刻当作认真生活的奖励'}</p><button data-buy="${r[2]}" data-name="${r[1]}">✦ ${r[2]} 星币</button></article>`).join('')}</div>`,
profile:()=>`<div class="page-head"><span>PLAYER PROFILE</span><h1>角色档案</h1><p>你不是一组数据，这些只是你走过的痕迹。</p></div><section class="profile card"><div class="portrait">安<span>LV.07</span></div><div class="bio"><span>微光探索者</span><h2>安安</h2><p>“慢慢走，也一直在自己的故事里。”</p><div class="stats"><div><b>42</b><small>完成任务</small></div><div><b>6</b><small>连续天数</small></div><div><b>12</b><small>当前章节</small></div></div></div><div class="skills"><h3>角色属性</h3>${[['行动力',74],['体力',58],['秩序',46],['心境',66]].map(x=>`<label>${x[0]}<em><i style="width:${x[1]}%"></i></em><b>${x[1]}</b></label>`).join('')}</div></section>`};
function render(){state.page=state.page||'today';$('#view').innerHTML=views[state.page]();$('#coins').textContent=state.coins;$('#pageName').textContent={today:'今日冒险',quests:'任务公会',journey:'世界地图',rewards:'奖励商店',profile:'角色档案'}[state.page];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));save()}
function addTask(){let title=prompt('给这项现实任务起个名字：');if(!title)return;state.tasks.push({id:Date.now(),title,note:'自定义支线 · 今天',type:'支线',xp:15,done:false});toast('✦ 新任务已加入冒险日志');render()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.page){state.page=b.dataset.page;render();$('.rail').classList.remove('open');return}if(b.dataset.task){let t=state.tasks.find(x=>x.id==b.dataset.task);t.done=!t.done;state.coins=Math.max(0,state.coins+(t.done?t.xp:-t.xp));toast(t.done?`+${t.xp} XP  任务完成！`:'任务已重新开启');render()}if(b.dataset.action==='add')addTask();if(b.dataset.action==='energy'){state.energy=state.energy>85?45:state.energy+10;render()}if(b.dataset.action==='random'){let a=['给一个很久没联系的人发问候','散步时走一条不同的路','认真听完一首没听过的歌','清理手机里的十张废片'];state.tasks.push({id:Date.now(),title:a[Math.floor(Math.random()*a.length)],note:'命运任务 · 今晚前',type:'随机',xp:20,done:false});toast('⚡ 命运任务已出现');render()}if(b.dataset.buy){let n=+b.dataset.buy;if(state.coins<n)return toast('星币还不够，再冒险一下吧');state.coins-=n;toast(`已兑换：${b.dataset.name}`);render()}if(b.id==='menu')$('.rail').classList.toggle('open')});render();
