const KEY='life-game-system-v3', todayKey=()=>new Date().toISOString().slice(0,10);
const initial={page:'today',coins:0,dayType:'',tasks:[],history:{},collections:[],unlocked:[]};
let state=initial;try{state={...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){}
const $=s=>document.querySelector(s), save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){let e=$('#toast');e.textContent=s;e.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.hidden=true,1800)}
function fmt(d=new Date()){return `${d.getMonth()+1}月${d.getDate()}日`}
function progress(){let n=new Date(),day=(n.getDay()+6)%7+1,dim=new Date(n.getFullYear(),n.getMonth()+1,0).getDate(),start=new Date(n.getFullYear(),0,1),doy=Math.floor((n-start)/86400000)+1,leap=new Date(n.getFullYear(),1,29).getMonth()===1;return {week:Math.round(day/7*100),month:Math.round(n.getDate()/dim*100),year:Math.round(doy/(leap?366:365)*100),day,dim,doy,days:leap?366:365}}
function ensureWork(){if(state.dayType==='work'&&!state.tasks.some(t=>t.date===todayKey()&&t.work))state.tasks.unshift({id:Date.now(),title:'完成今天的工作',type:'主线',xp:30,done:false,date:todayKey(),work:true})}
function todays(){return state.tasks.filter(t=>t.date===todayKey())}
function ring(p,face){return `<div class="ring" style="--p:${p*3.6}deg"><div><span>${face}</span><b>${p}%</b><small>今日完成度</small></div></div>`}
function taskCard(t){return `<article class="task ${t.done?'done':''}"><button data-task="${t.id}"><i>${t.done?'✓':t.type==='主线'?'★':t.type==='随机'?'?':'+'}</i><div><b>${esc(t.title)}</b><small>${t.type} · +${t.xp} 经历值</small></div></button></article>`}
function weekStrip(){let now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));return `<div class="week-strip">${[0,1,2,3,4,5,6].map(i=>{let d=new Date(monday);d.setDate(monday.getDate()+i);let current=d.toDateString()===now.toDateString();return `<div class="${current?'now':''}"><small>${'一二三四五六日'[i]}</small><b>${d.getDate()}</b><span>${current?'今天':''}</span></div>`}).join('')}</div>`}
function todayView(){ensureWork();let ts=todays(),done=ts.filter(t=>t.done).length,p=ts.length?Math.round(done/ts.length*100):0,face=p===100?'😎':p>=50?'😄':p?'🙂':'😴',pr=progress();return `<div class="welcome"><div><small>${new Date().getFullYear()}年 · ${['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][new Date().getDay()]}</small><h1>${fmt()}，今天怎么玩？</h1></div><button class="round" data-page="profile">⚙</button></div>${weekStrip()}<section class="hero">${ring(p,face)}<div class="hero-copy"><span class="tag">${state.dayType==='work'?'上班日':state.dayType==='rest'?'休息日':state.dayType==='free'?'自由安排':'还没选择今日模式'}</span><h2>${p===100?'今天圆满通关！':p?'已经向前走了一步':'不赶路，先选今天的模式'}</h2><p>${state.dayType?'只记录真正重要的事，不把生活变成打卡表。':'上班时间不固定没关系，每天由你自己触发。'}</p><div class="modes">${[['work','💼','上班'],['rest','🛋️','休息'],['free','🎈','自由安排']].map(x=>`<button class="${state.dayType===x[0]?'active':''}" data-mode="${x[0]}">${x[1]} ${x[2]}</button>`).join('')}</div></div></section><div class="title-row"><h2>今天的任务</h2><button data-add="支线">＋ 添加</button></div><div class="tasks">${ts.length?ts.map(taskCard).join(''):'<div class="empty">今天还没有任务。选一个模式，或添加一件真正想做的事。</div>'}</div><section class="time-card"><div><span>本周</span><b>${pr.week}%</b><em><i style="width:${pr.week}%"></i></em><small>第 ${pr.day} / 7 天</small></div><div><span>本月</span><b>${pr.month}%</b><em><i style="width:${pr.month}%"></i></em><small>第 ${new Date().getDate()} / ${pr.dim} 天</small></div><div><span>今年</span><b>${pr.year}%</b><em><i style="width:${pr.year}%"></i></em><small>第 ${pr.doy} / ${pr.days} 天</small></div></section>`}
function tasksView(){let all=[...state.tasks].reverse();return `<div class="page-title"><span>🎯</span><div><h1>任务中心</h1><p>主线只放重要方向，细碎工作不用逐条汇报。</p></div></div><div class="action-grid"><button data-add="主线"><i>★</i><b>新建主线</b><small>长期重要目标</small></button><button data-add="支线"><i>＋</i><b>新建支线</b><small>今天想推进的事</small></button><button data-random="1"><i>?</i><b>抽取随机任务</b><small>给生活一点惊喜</small></button></div><div class="tasks wide">${all.length?all.map(taskCard).join(''):'<div class="empty">还没有任务记录，从一件小事开始吧。</div>'}</div>`}
function calendarView(){let n=new Date(),y=n.getFullYear(),m=n.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),cells=''.padStart(first,' ').split('').map(()=>'<i></i>');for(let d=1;d<=days;d++){let key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,count=state.tasks.filter(t=>t.date===key&&t.done).length;cells.push(`<button class="${d===n.getDate()?'today':''}"><b>${d}</b>${count?`<span>${count}项</span>`:''}</button>`)}let p=progress();return `<div class="page-title"><span>📅</span><div><h1>${y}年${m+1}月</h1><p>看见时间，不是为了焦虑，而是更珍惜正在发生的生活。</p></div></div><section class="calendar"><div class="weeknames">${[...`一二三四五六日`].map(x=>`<b>${x}</b>`).join('')}</div><div class="days">${cells.join('')}</div></section><section class="time-card"><div><span>本周已过</span><b>${p.week}%</b><em><i style="width:${p.week}%"></i></em><small>还剩 ${7-p.day} 天</small></div><div><span>本月已过</span><b>${p.month}%</b><em><i style="width:${p.month}%"></i></em><small>还剩 ${p.dim-new Date().getDate()} 天</small></div><div><span>今年已过</span><b>${p.year}%</b><em><i style="width:${p.year}%"></i></em><small>还剩 ${p.days-p.doy} 天</small></div></section>`}
const achievementRules=[{id:'first',icon:'🌱',name:'第一枚书签',desc:'完成第一部作品',test:a=>a.length>=1},{id:'book1',icon:'📖',name:'故事初见',desc:'本月读完1本书',test:a=>monthDone(a,'书')>=1},{id:'book3',icon:'📚',name:'书页旅人',desc:'本月读完3本书',test:a=>monthDone(a,'书')>=3},{id:'movie3',icon:'🎬',name:'光影漫游',desc:'本月看完3部电影',test:a=>monthDone(a,'电影')>=3},{id:'series1',icon:'📺',name:'陪伴落幕',desc:'完整追完1部剧',test:a=>a.some(x=>x.kind==='剧集'&&x.status==='已完成')},{id:'mixed',icon:'🎪',name:'跨界玩家',desc:'完成3种不同类型的作品',test:a=>new Set(a.filter(x=>x.status==='已完成').map(x=>x.kind)).size>=3},{id:'feel5',icon:'💭',name:'感受收藏家',desc:'为5部作品留下感受',test:a=>a.filter(x=>x.note).length>=5}];
function monthDone(a,kind){let n=new Date(),prefix=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`;return a.filter(x=>x.kind===kind&&x.status==='已完成'&&(x.finished||'').startsWith(prefix)).length}
function refreshAchievements(){achievementRules.forEach(r=>{if(r.test(state.collections)&&!state.unlocked.includes(r.id)){state.unlocked.push(r.id);toast(`成就解锁：${r.name}`)}})}
function rewardsView(){refreshAchievements();let active=state.collections.filter(x=>x.status==='进行中'),recent=[...state.collections].reverse();return `<div class="page-title"><span>🧸</span><div><h1>我的收藏馆</h1><p>收藏陪伴过你的故事，也收藏当时的自己。</p></div></div><div class="collection-tools"><button data-collect="书">📖 记录一本书</button><button data-collect="电影">🎬 记录一部电影</button><button data-collect="剧集">📺 记录一部剧</button><button data-collect="游戏">🎮 记录一个游戏</button></div><div class="section-head"><h2>正在陪伴我</h2><span>${active.length} 项进行中</span></div><div class="shelf">${active.length?active.map(mediaCard).join(''):'<div class="empty">还没有正在进行的收藏。最近在看、在读或在玩的，都可以放进来。</div>'}</div><div class="section-head"><h2>文化足迹</h2><span>共 ${state.collections.length} 项</span></div><div class="shelf">${recent.length?recent.map(mediaCard).join(''):'<div class="empty">你的第一条文化收藏会出现在这里。</div>'}</div><div class="section-head"><h2>成就陈列柜</h2><span>${state.unlocked.length} / ${achievementRules.length} 已解锁</span></div><div class="badges">${achievementRules.map(r=>`<article class="${state.unlocked.includes(r.id)?'unlocked':'locked'}"><span>${state.unlocked.includes(r.id)?r.icon:'🔒'}</span><b>${r.name}</b><small>${r.desc}</small></article>`).join('')}</div>`}
function mediaCard(x){return `<article class="media"><div class="cover ${x.kind}">${x.kind==='书'?'📖':x.kind==='电影'?'🎬':x.kind==='剧集'?'📺':'🎮'}</div><div><span>${x.kind} · ${x.status}</span><h3>${esc(x.name)}</h3><p>${x.note?`“${esc(x.note)}”`:'还没有写下感受'}</p><button data-media="${x.id}">${x.status==='已完成'?'重新打开':'标记完成'}</button></div></article>`}
function profileView(){let completed=state.tasks.filter(t=>t.done).length,level=Math.floor(state.coins/100)+1;return `<div class="page-title"><span>🙂</span><div><h1>我的游戏档案</h1><p>这里只展示真实产生的记录，不再放演示数字。</p></div></div><section class="profile"><div class="avatar">安</div><div><small>等级 ${level}</small><h2>安安</h2><p>慢慢走，也一直在自己的故事里。</p></div><div class="stat"><b>${completed}</b><span>已完成任务</span></div><div class="stat"><b>${state.coins}</b><span>累计经历值</span></div><div class="stat"><b>${state.collections.length}</b><span>文化收藏</span></div></section><section class="settings"><h2>今日模式</h2><p>上班日会自动生成一条笼统主线“完成今天的工作”，不要求填写工作细项。</p><div class="modes">${[['work','💼','上班'],['rest','🛋️','休息'],['free','🎈','自由安排']].map(x=>`<button class="${state.dayType===x[0]?'active':''}" data-mode="${x[0]}">${x[1]} ${x[2]}</button>`).join('')}</div></section>`}
const views={today:todayView,tasks:tasksView,calendar:calendarView,rewards:rewardsView,profile:profileView};
function render(){state.page=views[state.page]?state.page:'today';$('#view').innerHTML=views[state.page]();$('#coins').textContent=state.coins;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));save()}
function add(type){let title=prompt(type==='主线'?'这条主线叫什么？':'今天想完成什么？');if(!title)return;state.tasks.push({id:Date.now(),title,type,xp:type==='主线'?30:15,done:false,date:todayKey()});toast('任务已加入今天');render()}
function addCollection(kind){let name=prompt(`想记录的${kind}叫什么？`);if(!name)return;let doing=confirm(`现在正在${kind==='书'?'读':kind==='游戏'?'玩':'看'}吗？\n确定＝进行中，取消＝已完成`),note=prompt('想留下一句感受吗？（可以留空）')||'';state.collections.push({id:Date.now(),kind,name,note,status:doing?'进行中':'已完成',started:todayKey(),finished:doing?'':todayKey()});refreshAchievements();save();render()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.page){state.page=b.dataset.page;return render()}if(b.dataset.mode){state.dayType=b.dataset.mode;ensureWork();toast('今日模式已更新');return render()}if(b.dataset.add)return add(b.dataset.add);if(b.dataset.collect)return addCollection(b.dataset.collect);if(b.dataset.media){let x=state.collections.find(a=>a.id==b.dataset.media);x.status=x.status==='已完成'?'进行中':'已完成';x.finished=x.status==='已完成'?todayKey():'';refreshAchievements();toast(x.status==='已完成'?'已收入文化足迹':'已放回正在陪伴我');return render()}if(b.dataset.random){let a=['拍下今天最喜欢的颜色','走一条平时不会走的路','认真听完一首歌','给未来的自己写一句话'];state.tasks.push({id:Date.now(),title:a[Math.floor(Math.random()*a.length)],type:'随机',xp:20,done:false,date:todayKey()});toast('随机任务出现了');return render()}if(b.dataset.task){let t=state.tasks.find(x=>x.id==b.dataset.task);if(!t)return;t.done=!t.done;state.coins=Math.max(0,state.coins+(t.done?t.xp:-t.xp));toast(t.done?`完成！获得 ${t.xp} 经历值`:'任务重新开启');return render()}});render();
